name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        
    - name: Build the Docker image
      run: |
           cd backend-springboot
           docker build . --file Dockerfile -t ${{secrets.DOCKER_USER}}/reactbackend:latest
             
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/reactbackend:latest
